---
- name: include vars from inventory.yaml
  include_vars:
    file: inventory.yaml
    name: inventory
    
- name: remove demo job template
  awx.awx.tower_job_template:
    name: "Demo Job Template"
    state: "absent"
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false

- name: remove demo project
  awx.awx.tower_project:
    name: "Demo Project"
    state: absent
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false

- name: remove demo credential
  awx.awx.tower_credential:
    name: "Demo Credential"
    credential_type: Machine
    state: absent
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false

- name: remove demo inventory
  awx.awx.tower_inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false

- name: Add Splunk project
  awx.awx.tower_project:
    name: "Splunk Demo"
    description: "Splunk demo files"
    organization: "Default"
    scm_type: git
    scm_url: https://github.com/redhat-gpst/splunk-demo.git
    state: present
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false

- name: Create vm remediation Job
  awx.awx.tower_job_template:
    name: "SPLUNK / Verify sudoers"
    job_type: "run"
    organization: "Default"
    inventory: "Workshop Inventory"
    project: "splunk demo"
    playbook: "sudoers.yml"
    credentials:
      - "Workshop Credential"
    state: "present"
    tower_username: admin
    tower_password: "{{ ansible_ssh_pass }}"
    tower_host: localhost
    validate_certs: false