---
- name: configure splunk es 
  hosts: localhost
  gather_facts: false
  become: yes

  collections:
     - awx.awx
     - splunk.es

  roles:
    - configure_rhel
    - configure_splunk
    - configure_tower
       
- name: configure splunk forwarder on node1
  hosts: node1
  gather_facts: false
  become: yes

  roles:
    - configure_node1