---
- name: configure splunk es 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  collections:
     - awx.awx
     - splunk.es

  roles:
    - configure_rhel
    - configure_splunk
    - configure_tower
       
- name: configure splunk forwarder on node1
  hosts: node1
  gather_facts: false
  become: yes

  roles:
    - configure_node1

- name: print url for splunk 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  tasks:
    
    - name: gret url for splunk
      find:
        paths: /etc/letsencrypt/live
        file_type: directory
        use_regex: yes
        patterns: 'student.\..*'
      register: url

    - debug:
        msg: "Splunk URL: http://{{ url.files[0].path | regex_search('student.*') }}:8000"
