---
- name: convert workshop inventory ini to yaml
  shell: ansible-inventory -i ~/lab_inventory/hosts -y --list > inventory.yaml
  become: no

- name: install collections
  shell: ansible-galaxy collection install awx.awx splunk.es
  
- name: verify some programs are installed
  dnf:
    name:
      - nano
      - nmap
      - vim
      - wget
    state: present