---
- name: convert workshop inventory ini to yaml
  shell: ansible-inventory -i ~/lab_inventory/hosts -y --list > inventory.yaml
  become: no

- name: include vars from inventory.yaml
  include_vars:
    file: inventory.yaml
    name: inventory

- name: verify some programs are installed
  dnf:
    name:
      - nano
      - nmap
      - vim
      - wget
    state: present